In [26]:
import open3d as o3d
import numpy as np

# Create an example point cloud
points = np.random.rand(20, 3)  # Generates 100 random points in 3D space
pcd = o3d.geometry.PointCloud()
pcd.points = o3d.utility.Vector3dVector(points)

# Save the point cloud as a PCD file
o3d.io.write_point_cloud("example.pcd", pcd)


True

In [27]:
import open3d as o3d
import numpy as np

# Generate some example data (vertices and faces)
vertices = np.array([[0, 0, 0], [1, 0, 0], [1, 1, 0], [0, 1, 0], [0.5, 0.5, 1]])
faces = np.array([[0, 1, 2], [0, 2, 3], [0, 1, 4], [1, 2, 4], [2, 3, 4], [3, 0, 4]])

# Create a mesh from the vertices and faces
mesh = o3d.geometry.TriangleMesh()
mesh.vertices = o3d.utility.Vector3dVector(vertices)
mesh.triangles = o3d.utility.Vector3iVector(faces)

# Save the mesh to a .ply file
o3d.io.write_triangle_mesh("example_mesh.ply", mesh)


True

In [30]:
import open3d as o3d
import numpy as np

print("Load a ply point cloud, print it, and render it")
ply_point_cloud = o3d.data.PLYPointCloud()

pcd = o3d.io.read_point_cloud("T:\Python\AYD\my_point_cloud.ply")

print(np.asarray(pcd.points))
o3d.visualization.draw_geometries([pcd],
                                  zoom=0.3412,
                                  front=[0.4257, -0.2125, -0.8795],
                                  lookat=[2.6172, 2.0475, 1.532],
                                  up=[-0.0694, -0.9768, 0.2024])

Load a ply point cloud, print it, and render it
[Open3D WARNING] Read PLY failed: unable to read file: T:\Python\AYD\my_point_cloud.ply
[[ 0.00000000e+000 -9.68750000e-001  8.06166914e-320]
 [-1.80418078e+230  4.23650451e-305 -1.40604622e+227]
 [ 6.42125255e-077 -9.77995753e-001  1.19251358e-302]
 ...
 [ 0.00000000e+000  0.00000000e+000  0.00000000e+000]
 [ 0.00000000e+000  0.00000000e+000  0.00000000e+000]
 [ 0.00000000e+000  0.00000000e+000  0.00000000e+000]]


In [ ]:
# import open3d as o3d
# import numpy as np

# # Assuming ply_point_cloud is an instance of a class with a 'path' attribute.
# ply_point_cloud = o3d.data.PLYPointCloud()

# # Get the path
# ply_path = ply_point_cloud.path

# # Load the point cloud
# pcd = o3d.io.read_point_cloud(ply_path)

# # Print the point cloud and its path
# print(pcd)
# print(np.asarray(pcd.points))
# print(f'Path to the PLY file: {ply_path}')

# # Save the point cloud
# o3d.io.write_point_cloud("output.ply", pcd)


In [2]:
# import csv
# import open3d as o3d
# # Initialize an empty list to hold your data
# data = []

# # Assuming your CSV file is named "your_file.csv"
# with open('T:\Python\AYD\MAINDF.csv', newline='') as csvfile:
#     reader = csv.reader(csvfile)
#     for row in reader:
#         # Assuming the CSV has three columns, change indices as needed
#         data.append([float(row[0]), float(row[1]), float(row[2])])

# # Convert the list of lists into a NumPy array if needed
# import numpy as np
# data_array = np.array(data)

# points = np.array(data_array)

# # Create a PointCloud object
# pcd = o3d.geometry.PointCloud()
# pcd.points = o3d.utility.Vector3dVector(points)

# # Save the point cloud as a PLY file
# o3d.io.write_point_cloud("my_point_cloud.ply", pcd)

# # Now you can load the PLY file
# loaded_pcd = o3d.io.read_point_cloud("my_point_cloud.ply")

# # Print and visualize the loaded point cloud
# print(loaded_pcd)
# o3d.visualization.draw_geometries([loaded_pcd])

# # Now, 'data' contains your CSV data as a list of lists, and 'data_array' is a NumPy array.


PointCloud with 16415 points.


In [18]:
import open3d as o3d

loaded_pcd = o3d.io.read_point_cloud("updated_data.ply")

print(loaded_pcd)
o3d.visualization.draw_geometries([loaded_pcd],zoom=0.3412,
                                  front=[0.4257, -0.2125, -0.8795],
                                  lookat=[2.6172, 2.0475, 1.532],
                                  up=[-0.0694, -0.9768, 0.2024])

PointCloud with 16415 points.


In [11]:
print("Downsample the point cloud with a voxel of 0.05")
downpcd = loaded_pcd.voxel_down_sample(voxel_size=0.05)
o3d.visualization.draw_geometries([downpcd],
                                  zoom=0.3412,
                                  front=[0.4257, -0.2125, -0.8795],
                                  lookat=[2.6172, 2.0475, 1.532],
                                  up=[-0.0694, -0.9768, 0.2024])

Downsample the point cloud with a voxel of 0.05


In [12]:
print("Recompute the normal of the downsampled point cloud")
downpcd.estimate_normals(
    search_param=o3d.geometry.KDTreeSearchParamHybrid(radius=0.1, max_nn=30))
o3d.visualization.draw_geometries([downpcd],
                                  zoom=0.3412,
                                  front=[0.4257, -0.2125, -0.8795],
                                  lookat=[2.6172, 2.0475, 1.532],
                                  up=[-0.0694, -0.9768, 0.2024],
                                  point_show_normal=True)

Recompute the normal of the downsampled point cloud


In [8]:
import pandas as pd
import open3d as o3d
import numpy as np

# Step 1: Read the CSV file
csv_data = pd.read_csv('T:\Python\AYD\MAIN_DF.csv')  # Replace 'data.csv' with your CSV file's name

# Step 2: Prepare the data
# For example, if your CSV file has x, y, z coordinates:
x = csv_data['lat'].values
y = csv_data[' lon'].values
z = csv_data[' elevation'].values

# Step 3: Read the existing PLY file (if it exists)
if o3d.io.read_point_cloud('existing_data.ply'):
    point_cloud = o3d.io.read_point_cloud('existing_data.ply')
else:
    # Create a new point cloud if 'existing_data.ply' doesn't exist
    point_cloud = o3d.geometry.PointCloud()

# Step 4: Add data to the PLY file
# Assuming x, y, z are numpy arrays
# Convert them into a single numpy array of shape (N, 3)
xyz = np.column_stack((x, y, z))

# Create an Open3D PointCloud from the numpy array
new_points = o3d.geometry.PointCloud()
new_points.points = o3d.utility.Vector3dVector(xyz)

# Concatenate the new points with the existing points
point_cloud.points = o3d.utility.Vector3dVector(np.vstack([point_cloud.points, new_points.points]))

# Step 5: Save the updated PLY file
o3d.io.write_point_cloud('updated_data.ply', point_cloud)


[Open3D WARNING] Read PLY failed: unable to open file: existing_data.ply
[Open3D WARNING] Read PLY failed: unable to open file: existing_data.ply


True